services:
  nginx:
    labels:
      - konta.managed=true
      
    image: nginx:latest
    restart: unless-stopped

    # Mount website content
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - "80:80"
